### ISSUE TITLE
Feature Request:  Extend Unit option into set_option_active service

### ISSUE THREAD

**Issue by crhammock** [DavidMStraub/homeassistant-homeconnect#129]
I have been starting to use the Home Assistant HomeConnect integration with my oven thanks to the recent feature.  However I am unable to get the set_option_active service to work.  The below detail from the API tool suggests the feature is only available on ovens yet the example perimeters use a dryer.  When trying to perform such tasks as change the temperature or duration of the active program I get the following error

Error handling message: extra keys not allowed @ data['unit']. Got None

https://apiclient.home-connect.com/?url=https%3A//apiclient.home-connect.com/hcsdk-production.yaml&client_id=YOUR_CLIENT_ID#/programs/set_active_program_options

I am using the following YAML

```
service: home_connect_beta.set_option_active
data:
  entity_id: switch.oven_power
  key: Cooking.Oven.Option.SetpointTemperature
  value: 180
  unit: °C
```

**Comment by DavidMStraub** [comment]
Good point. Can you try with the latest commit on `master`?

**Comment by crhammock** [comment]
Thanks David, I grabbed the latest files and rebooted.

First I tried the below, the format was defined by the "Fill Example Data" hyperlink via yaml mode

```
service: home_connect_beta.set_option_active
data:
  entity_id: switch.oven_power
  key: Cooking.Oven.Option.SetpointTemperature
  value: 180
  unit: °C
```

This produced the below error

> websocket_api script: Error executing script. Unexpected error for call_service at pos 1: {'key': 'SDK.Error.InvalidOptionValue', 'description': 'Key Cooking.Oven.Option.SetpointTemperature has unexpected type or value 180'}

I also tried the below, based on the format used for the start program service

```
service: home_connect_beta.set_option_active
data:
  entity_id: switch.oven_power
  options:
    - key: Cooking.Oven.Option.SetpointTemperature
      value: 200
      unit: °C
```

This produced the error 

> websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['options']

Don't know if that helps, I have tried a load of different scenarios and formats but they all seem to provide similar log output and results.
