### ISSUE TITLE
"start_program" does not work with example data

### ISSUE THREAD

**Issue by asev** [DavidMStraub/homeassistant-homeconnect#130]
I get this error: `expected a list for dictionary value @ data['options']. Got None`

Example data should look like this
```
service: home_connect_beta.start_program
data:
  entity_id: switch.dishwasher_power
  program: Dishcare.Dishwasher.Program.Auto2
  options:
    - key: BSH.Common.Option.StartInRelative
      value: 1800
      unit: seconds
```

instead of 
```
service: home_connect_beta.start_program
data:
  entity_id: switch.dishwasher_power
  program: Dishcare.Dishwasher.Program.Auto2
  option_key: BSH.Common.Option.StartInRelative
  option_value: 1800
  option_unit: seconds
```
