### ISSUE TITLE
Redirekt url

### ISSUE THREAD

**Issue by Vabis1010** [DavidMStraub/homeassistant-homeconnect#140]
After reinstall home assistant 2022.6. I get problem when i try to install integration with redirekt url or client not valid. Have the same  yaml as before the homeassistant reinstall. Can anybody help me out?

**Comment by vonNiklasson** [comment]
It looks like the integration has changed to use the common UEL handler.

In your home connect application, change the `redirect URL` to `https://my.home-assistant.io/redirect/oauth` instead

**Comment by danys94** [comment]
I have changed as suggested redirect URL to https://my.home-assistant.io/redirect/oauth and I am gettings this:
  "error_description": "request rejected by client authorization authority (developer portal)",

**Comment by Vabis1010** [comment]
You have to put this in your config.yaml too. Toen ik works.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by danys94** [comment]
Where to? Under which parameter? 
```
homeassistant:
  external_url: "http://10.0.10.35:8123"
  internal_url: "http://10.0.10.35:8123"
home_connect:
  client_id: XXX
  client_secret: XXX
```
this is all I have

**Comment by Vabis1010** [comment]
Simple Wriite http: and toen the rest as in the picture. Use your own ipadres, not mine.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by danys94** [comment]
I do not see any picture, unfortunately.

**Comment by Vabis1010** [comment]
What abortus now?

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by danys94** [comment]
Still nothing :(

**Comment by Vabis1010** [comment]
You have an emailadres i can sent it  to?

**Comment by danys94** [comment]
Thank you, it worked! Here is how it should be setup:

```
home_connect:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret
http:
  base_url: http://10.0.10.35:8123
```
