### ISSUE TITLE
Card example

### ISSUE THREAD

**Issue by k1rd3rf** [DavidMStraub/homeassistant-homeconnect#82]
I've created a card for my devices that I wanted to share, and I didn't know where to put it.

This card involves usage of two other custom components found on HACS (`custom:auto-entities` and `custom:decluttering-card`). `custom:decluttering-card` can of course be dropped, but I have more than one device so I wanted to avoid duplication.

The card:
```
type: vertical-stack
title: Kaffemaskin
cards:
  - type: custom:decluttering-card
    template: home_connect
    variables:
      - machine_type: "coffee_maker"
```

The decluttering template:
```
card:
  type: vertical-stack
  cards:
    - type: custom:auto-entities
      card:
        type: glance
      filter:
        include:
          - entity_id: "*[[machine_type]]*"
            domain: switch
            options:
              tap_action:
                action: toggle
          - entity_id: "*[[machine_type]]*"
            not:
              domain: switch
        exclude:
          - entity_id: "switch.[[machine_type]]_program*"
          - state: "unavailable"
      unique: true
    - type: conditional
      conditions:
        - entity: "switch.[[machine_type]]_power"
          state: "on"
      card:
        type: custom:auto-entities
        card:
          type: glance
          title: Program
          columns: 3
        filter:
          include:
            - entity_id: "switch.[[machine_type]]_program*"
              options:
                tap_action:
                  action: toggle
```

The result:
<img width="508" alt="Card rendered" src="https://user-images.githubusercontent.com/1519459/81273908-de9f0100-904f-11ea-8af3-a966d3e59033.png">

Some notes:
- I've customised the names for the programs
- The program card will only display of the power state is on. 
- I want to give a big thank you for creating this integration. I can finally instruct my google home to make me a coffee :D

**Comment by zufivan** [comment]
Hi, first  thanks very much @DavidMStraub for the development! I will share my configuration about coffe maker, unfortunately work only with version 0.3 because this solution use attributes from power switch, this attributes are removed in release 1.0, see release notes.
I hope in the future David can create custom sensor to show more information.
**Following My Config:**

sensor.yaml

```
 - platform: template # Operation State Macchina Caffe
    sensors:
      template_macchina_caffe_operation_state:
        friendly_name: Stato Funzionamento
        icon_template: mdi:play-protected-content
        value_template: >
          {% if state_attr('switch.macchina_caffe', 'operation_state') == 'run' %}
            In Funzione
          {% elif state_attr('switch.macchina_caffe', 'operation_state') == 'inactive' %}
            Non Attivo
          {% elif state_attr('switch.macchina_caffe', 'operation_state') == 'ready' %}
            Acceso
          {% elif state_attr('switch.macchina_caffe', 'operation_state') == 'delayedstart' %}
            Accensioen Ritardata
          {% elif state_attr('switch.macchina_caffe', 'operation_state') == 'pause' %}
            Pausa
          {% elif state_attr('switch.macchina_caffe', 'operation_state') == 'actionrequired' %}
            Azione Richiesta
          {% elif state_attr('switch.macchina_caffe', 'operation_state') == 'finished' %}
            Finito
          {% elif state_attr('switch.macchina_caffe', 'operation_state') == 'error' %}
            Errore
          {% elif state_attr('switch.macchina_caffe', 'operation_state') == 'aborting' %}
            Annullato
          {% endif %}

- platform: template # Remote Start Allowed Macchina Caffe
    sensors:
      template_macchina_caffe_remote_start_allowed:
        friendly_name: Consenti Avvio Remoto
        icon_template: mdi:account-check-outline
        value_template: >
          {% if is_state_attr('switch.macchina_caffe', 'remote_control_start_allowed', true) %}
            Autorizzato
          {% elif is_state_attr('switch.macchina_caffe', 'remote_control_start_allowed', false) %}
            Non Autorizzato
          {% endif %}

 - platform: template # Active Program Macchina Caffe
    sensors:
      template_macchina_caffe_active_program:
        friendly_name: Programma In Funzione
        icon_template: mdi:ballot-recount-outline
        value_template: >
          {% if state_attr('switch.macchina_caffe', 'active_program') == 'appliance_on_rinsing' %}
            Risciaquo
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'appliance_off_rinsing' %}
            Risciaquo
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'ristretto' %}
            Ristretto
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'espresso' %}
            Espresso
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'espresso_doppio' %}
            Espresso Doppio
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'espresso_macchiato' %}
            Espresso Macchiato
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'coffee' %}
            Caffè
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'cappuccino' %}
            Cappuccino
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'latte_macchiato' %}
            Latte Macchiato
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'bottomheating' %}
            Riscaldamento Inferiore
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'caffe_latte' %}
            Caffè Latte
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'milkFroth' %}
            Schiuma Latte
          {% elif state_attr('switch.macchina_caffe', 'active_program') == 'warm_milk' %}
            Latte Caldo
          {% endif %}


  - platform: template # Time Remaining Macchina Caffe
    sensors:
      template_macchina_caffe_time_remaining:
        friendly_name: Tempo Rimanente
        icon_template: mdi:timer-sand
        value_template: >-
          {% set seconds = states('sensor.macchina_caffe_remaining_program_time') | int %}
          {% set minutes = ((seconds % 3600) / 60) | int %}
          {% set hours = ((seconds % 86400) / 3600) | int %}
          {%- if hours -%}
            {%- if hours == 1 -%}
              1 ora
            {%- else -%}
              {{ hours }} ore
            {%- endif -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if seconds > 59 and minutes > 1 -%}
            {{minutes}} minuti
          {%- endif -%}
          {%- if seconds > 59 and minutes == 1 -%}
            {{minutes}} minuto
          {%- endif -%}
          {%- if seconds <= 59 and seconds >= 1 -%}
            {{ seconds }} secondi
          {%- endif -%}
          {%- if seconds < 1 -%}
            {{ seconds }}
          {%- endif -%}

  - platform: template # Fill Quantity Macchina Caffe
    sensors:
      template_macchina_caffe_fill_quantity:
        friendly_name: "Quantità Bevanda"
        icon_template: mdi:cup
        unit_of_measurement: 'ml'
        value_template: "{{ state_attr('switch.macchina_caffe', 'fill_quantity') }}"

  - platform: template # Bean Amount Macchina Caffe
    sensors:
      template_macchina_caffe_bean_amount:
        friendly_name: "Quantità Caffè"
        icon_template: mdi:coffee-outline
        value_template: >
          {% if state_attr('switch.macchina_caffe', 'bean_amount') == 'very_mild' %}
            Leggero
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'mild' %}
            Molto Leggero
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'mild_plus' %}
            Leggero plus
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'normal' %}
            Normale
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'normal_plus' %}
            Normale +
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'strong' %}
            Forte
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'strong_plus' %}
            Forte +
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'very_strong' %}
            Molto Forte
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'very_strong_plus' %}
            Molto Forte +
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'extra_strong' %}
            Extra Forte
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'double_shot' %}
            Doppia Porzione
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'double_shot_plus' %}
            Doppia Porzione +
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'double_shot_plus_plus' %}
            Doppia Porzione + +
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'triple_shot' %}
            Tripla Porzione
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'triple_shot_plus' %}
            Tripla Porzione +
          {% elif state_attr('switch.macchina_caffe', 'bean_amount') == 'coffee_ground' %}
            Caffè in Polvere
          {% endif %}

  - platform: template # Coffee Temperature Macchina Caffe
    sensors:
      template_macchina_caffe_temperature:
        friendly_name: "Temperatura Caffè"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('switch.macchina_caffe', 'coffee_temperature') [:2] }}"

  - platform: template # Avviso Drip Tray Full Macchina Caffe
    sensors:
      template_macchina_caffe_drip_tray_full:
        friendly_name: "Avviso"
        icon_template: mdi:alert-box-outline
        value_template: >
          {% if state_attr('switch.macchina_caffe', 'drip_tray_full') == 'present' %}
            Svuotare Raccogligoccie
          {% endif %}

  - platform: template # Avviso Water Tank Empty Acqua Macchina Caffe
    sensors:
      template_macchina_caffe_water_tank_empty:
        friendly_name: "Avviso"
        icon_template: mdi:alert-box-outline
        value_template: >
          {% if state_attr('switch.macchina_caffe', 'water_tank_empty') == 'present' %}
            Riempire Acqua
          {% endif %}

  - platform: template # Avviso Bean Container Empty Macchina Caffe
    sensors:
      template_macchina_caffe_bean_container_empty:
        friendly_name: "Avviso"
        icon_template: mdi:alert-box-outline
        value_template: >
          {% if state_attr('switch.macchina_caffe', 'bean_container_empty') == 'present' %}
            Riempire Chicci Caffè
          {% endif %}

```

**I use custom auto-entities in lovelace:**
ui-lovelace.yaml
```
      - type: custom:auto-entities # Macchina Caffe
        show_empty: false
        show_header_toggle: false
        show_state: false
        card:
          title: Macchina Caffè
          type: entities
          show_header_toggle: false
        filter:
          include:
            - type: section
              label: Stato
            - entity_id: switch.macchina_caffe
            - entity_id: sensor.template_macchina_caffe_operation_state
            - entity_id: sensor.template_macchina_caffe_remote_start_allowed
            - entity_id: sensor.template_macchina_caffe_active_program
            - entity_id: sensor.macchina_caffe_program_progress
            - entity_id: sensor.template_macchina_caffe_time_remaining
            - entity_id: sensor.template_macchina_caffe_fill_quantity
            - entity_id: sensor.template_macchina_caffe_bean_amount
            - entity_id: sensor.template_macchina_caffe_temperature
            - entity_id: sensor.template_macchina_caffe_drip_tray_full
            - entity_id: sensor.template_macchina_caffe_water_tank_empty
            - entity_id: sensor.template_macchina_caffe_bean_container_empty

          exclude:
            - state: "Non disponibile"
            - state: "unavailable"
            - state: "0 minuti"
            - state: "0"
            - state: "100"
            - state: "Non Attivo"
            - state: ""

```
**I create alaso an automation to set all state to "0" (some times Program Progress was stopped at 95%)**
automation.yaml
```

- id: Home Connect Reset status Macchina Caffe after prog_off
  alias: Home Connect Reset status Macchina Caffe after prog_off
  description: Home Connect Reset status Macchina Caffe after prog_off
  trigger:
  - entity_id: sensor.template_macchina_caffe_operation_state
    platform: state
    to: 'Acceso'
  condition: []
  action:
  - delay: 00:00:05
  - data:
      entity_id: sensor.template_macchina_caffe_active_program
      state: 0
    service: python_script.set_state
  - data:
      entity_id: sensor.macchina_caffe_program_progress
      state: 0
    service: python_script.set_state
  - data:
      entity_id: sensor.template_macchina_caffe_fill_quantity
      state: 0
    service: python_script.set_state
  - data:
      entity_id: sensor.template_macchina_caffe_bean_amount
      state: 0
    service: python_script.set_state
  - data:
      entity_id: sensor.template_prog_macchina_caffe_time_remaining
      state: 0
    service: python_script.set_state
  - data:
      entity_id: sensor.template_macchina_caffe_temperature
      state: 0
    service: python_script.set_state

```
Running Program:
![Running Program](https://user-images.githubusercontent.com/47624226/81340285-dc6c8f00-90af-11ea-80d3-dd97438d78e3.PNG)
Power ON:
![Power On](https://user-images.githubusercontent.com/47624226/81340292-e2fb0680-90af-11ea-94ab-1ed46209a8c5.PNG)
With Warning:
![With Warning_water_tank_empty](https://user-images.githubusercontent.com/47624226/81340310-ec846e80-90af-11ea-9041-b43e05d541bb.PNG)
